### ISSUE TITLE
Apparently broken markdown in some posts

### ISSUE THREAD

**Issue by cruxicheiros** [cds-snc/digital-canada-ca#1024]
**The issue:**
Some posts on the digital.canada.ca website are presenting with what appears to be broken markdown.

Asterisks (`*`) appear out of context in the posts in ways which look like the markdown syntaxes for bolding and bulleted lists.

**Why it is an issue:**
It makes the posts harder to read. I am able to work out what the post is actually trying to say because I know markdown, but a person who did not know it would have a harder time.

**Examples:**
[Gracefully Degrading React (2018/08)](https://digital.canada.ca/2018/08/08/supporting-users-gracefully-degrading-react/) 
[Digital words: Mots vs Maux (2018/08)](https://digital.canada.ca/2018/08/17/lexicon/)

**Notes:**
I don't work on this project and haven't looked into its setup so I don't know the cause of this. I also haven't done thorough testing.

However, if you have recently updated your site to something which uses a different markdown parser, this could be the cause.

Cheers.

**Comment by khalidelaggan** [comment]
thank you @dsamojlenko for your collaboration, this is now resolved.
