### ISSUE TITLE
Extra horizontal padding on mobile

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/digital-canada-ca#1025]
Hello,

The products and resources sections have too much horizontal padding on mobile making it hard to read. 

![Screenshot_2019-09-03-08-47-19-830_com android chrome](https://user-images.githubusercontent.com/295709/64149944-814f1200-ce27-11e9-9383-76fa66563293.png)

Update: it seems the issue appears for all content pages.

**Comment by timarney** [comment]
@khalidelaggan @victoriachanimal was likely introduced here https://github.com/cds-snc/digital-canada-ca/pull/978

<hr>

<img width="376" alt="Screen Shot 2019-09-03 at 11 45 28 AM" src="https://user-images.githubusercontent.com/62242/64188561-ab60fe00-ce40-11e9-9b90-2cb45c85252b.png">

<hr>
<img width="321" alt="Screen Shot 2019-09-03 at 11 46 29 AM" src="https://user-images.githubusercontent.com/62242/64188612-bc117400-ce40-11e9-98b0-dfbb975fcfcd.png">

**Comment by timarney** [comment]
Actually https://github.com/cds-snc/digital-canada-ca/pull/996

**Comment by victoriachanimal** [comment]
@AntoineAugusti @timarney @khalidelaggan Thanks for flagging this! Was my doing - will remove that today and send a PR over for your review.

**Comment by AntoineAugusti** [comment]
Closing as the issue was fixed in the PR. Thanks
