### ISSUE TITLE
Menu button not visible on some pages

### ISSUE THREAD

**Issue by AntoineAugusti** [cds-snc/digital-canada-ca#1057]
![Screenshot_2019-09-10-10-01-07-668_com android chrome](https://user-images.githubusercontent.com/295709/64595350-0b602300-d3b2-11e9-99d7-bdafbd92e347.png)
The menu button isn't white on some pages, here the blog index. It's white on the homepage as intended.

**Comment by pcraig3** [comment]
I came here to say this!

**Comment by khalidelaggan** [comment]
Our new menu design has been deployed now, and it did address this UI issue.
Thank you so much for your feedback
