### ISSUE TITLE
Image cut off for mobile

### ISSUE THREAD

**Issue by timarney** [cds-snc/digital-canada-ca#1309]
Link: https://digital.canada.ca/2020/03/09/leading-by-example-a-sit-down-with-our-partner-at-the-rcmp

**Issue:**

<img width="400" alt="Screen Shot 2020-03-10 at 9 53 42 AM" src="https://user-images.githubusercontent.com/62242/76319149-26eeac80-62b5-11ea-98ea-95e3afa30348.png">

<img width="430" alt="Screen Shot 2020-03-10 at 9 56 18 AM" src="https://user-images.githubusercontent.com/62242/76319349-77fea080-62b5-11ea-8cd9-b48dea3979f1.png">

**Comment by victoriachanimal** [comment]
Thanks for flagging! Changed banner image to one that adapts better on mobile screens in #1310.
