### ISSUE TITLE
Create a security.txt file to align with industry standard for vulnerability disclosure practices

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/digital-canada-ca#1492]
Contact: mailto:security@cds-snc.ca
Contact: mailto:securite@cds-snc.ca
Encryption: https://domain/<link_to_pgp>
Acknowledgments: https://domain.com/<link_to_shoutouts_for_awesome_researchers>
Preferred-Languages: en,fr
Canonical: https://digital.canada.ca/.well-known/security.txt
Policy: https://domain.com/<link_to_security_policy>
Hiring: https://domain.com/<link_to_careers_in_security>

Draft content above based on spec defined here https://securitytxt.org/

**Comment by AntoineAugusti** [comment]
Curious if you'd like to have this on products as well (as an example at https://notification.alpha.canada.ca/.well-known/security.txt)

**Comment by obrien-j** [comment]
Totally forgot about this ticket. :)

Thanks for the reminder. 100%, I'd actually like to standardize on a CDS wide vulnerability disclosure policy ala https://github.com/cds-snc/covid-alert-documentation/blob/main/VulnerabilityDisclosurePolicy.md

If you want to create an issue/ticket in the Notify backlog, and tag me in, happy to get this sorted sooner rather than later.

**Comment by AntoineAugusti** [comment]
Created an issue in the backlog for Notify. I guess a sample vulnerability disclosure policy could be added to this repo https://github.com/cds-snc/.github and linked to?
