### ISSUE TITLE
Implement HSTS 

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/digital-canada-ca#163]
In support of the whole HTTPS Everywhere initiative and our own commitment to security by design, deploy HSTS (and preload if possible) for our teams website.

https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/

Above link references AWS literature on deploying HSTS to cloudfront. Not ideal, but it is what it is.

**Comment by dsamojlenko** [comment]
this was done a little while ago
