### ISSUE TITLE
Translate README

### ISSUE THREAD

**Issue by lchski** [cds-snc/digital-canada-ca#182]
Can follow the example of our NRCAN API and e-briefing repos and include the English and French versions in the same file, with a skip link at the start.

**Comment by sboots** [comment]
Maybe we can chat for 5 or 10 at the next dev meetup – @lchski and I put together some notes based on discussions with Annie in the summer.

**Comment by obrien-j** [comment]
Bumping this for translation.

**Comment by lchski** [comment]
Submitted for translation this morning!
