### ISSUE TITLE
Update Citizenship service name and description on product page

### ISSUE THREAD

**Issue by kyliehavelock** [cds-snc/digital-canada-ca#201]
https://digital.canada.ca/products/

Update service name to
**Reschedule a Citizenship Test**

Update service description to
**A service that allows people to reschedule their citizenship tests online, providing a simpler, easier and faster user experience for applicants.**

**Comment by ewootton** [comment]
@anikbrazeau would you be able to grab me the French translation for this?

**Comment by anikbrazeau** [comment]
Submitted a pull request that addresses this issue.
