### ISSUE TITLE
Upgrade Hugo

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/digital-canada-ca#2052]
We're using quite an old version at this point (0.55). This will involve many breaking changes.

**Comment by dj2** [comment]
Until we've upgraded our Hugo, is there an easy way to get the correct Hugo version on a dev machine? If I use the one from brew I'm getting something in the 0.8x range which seems to have issues rendering things like the blog cards on the homepage.

**Comment by brdunfield** [comment]
I unfortunately did not find an easy way.

I had to grab the 0.55 release tarball here: https://github.com/gohugoio/hugo/releases/tag/v0.55.6

And followed instructions for installing from tarball: https://bwaycer.github.io/hugo_tutorial.hugo/tutorials/installing-on-mac/#from-tarball

**Comment by dj2** [comment]
Just as a note for anyone else, you need the `extended` hugo release, they're on the bottom of the list. If you don't have extended you'll get an error like `error: failed to transform resource: TOCSS:`

**Comment by dj2** [comment]
One bug to be fixed: the blog posts don't show up on the homepage with newer Hugo. For some reason the blog array has one item in it which isn't really a blog post. It seems like the section doesn't have any content like it does in the older Hugo version?

**Comment by katedee** [comment]
Another possible side effect with the newer version: hot builds don't seem to be working consistently if you have a newer version of Hugo
