### ISSUE TITLE
Implement redesigned footer

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2120]
This issue is to implement the new footer for the website.

![image](https://user-images.githubusercontent.com/9611/113763504-be584600-96e7-11eb-93a8-140afdedd613.png)

Figma: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-(Copy-w%2F-March-2021-Updates)?node-id=132%3A8007

**Comment by victoriachanimal** [comment]
English mockup with links: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=132%3A8007

French mockup with links: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=652%3A7

^ Note: The above mockups include all available links in Footer menu, with the exception of 3 that need to be built / revamped, including _Resources_, _Past projects_ and _Meet the team_.
