### ISSUE TITLE
Create `Our Values` page

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2123]
We need to create a new page for the site `Our Values`.

![image](https://user-images.githubusercontent.com/9611/113764485-05930680-96e9-11eb-85d1-a268bb01136e.png)

The `Subscribe to newsletter` is the same as the main page so this should be a shared with #2121 

Figma: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-(Copy-w%2F-March-2021-Updates)?node-id=132%3A8007

**Comment by victoriachanimal** [comment]
See CDS website design system (CSS styles) here: https://digital-canada-system.netlify.app/components/detail/color.html

**Comment by dj2** [comment]
The top part of this page is now done. Still need to add the 3 gray boxes at the bottom.

**Comment by katedee** [comment]
Bottom half/ cta boxes handled in #2383 . Considering this done now :)
