### ISSUE TITLE
Implement new Career page design

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2124]
The careers page has been updated and needs to be implemented. This is currently the [join our team](https://digital.canada.ca/join-our-team/) page.

![image](https://user-images.githubusercontent.com/9611/113765617-81da1980-96ea-11eb-990b-65366cacf580.png)

For this issue, we'll leave off the `get notified` portion, just getting the page into the new design and we'll file a followup for the notification portion.

The `current openings` are just examples and should be populated the same way as the current careers page.

The `Our Values` section will link to #2123 which, if the issue isn't complete, we'll need to leave the link out. But, if possible we should look at doing the our values page first.

Figma: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-(Copy-w%2F-March-2021-Updates)?node-id=132%3A8007

**Comment by victoriachanimal** [comment]
See CDS website design system (CSS styles) here: https://digital-canada-system.netlify.app/components/detail/color.html

**Comment by victoriachanimal** [comment]
English mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=132%3A8007
French mockup: https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Revamp-Work-in-Progress?node-id=652%3A7

**Comment by victoriachanimal** [comment]
Thanks @katedee !

Adding that the external-facing categories that show up on this Careers page (whenever a new job is posted) are slightly different than the internal-facing categories we have on the new _[Meet the team](https://digital.canada.ca/meet-the-team/)_ page.

List of categories (which will need to be added to Strapi CMS) can be found here: https://docs.google.com/document/d/1zvLZDadF8snrevG6x0aGHoHoPed4BKPZ_U_55RlzqzE/edit
