### ISSUE TITLE
Update top level menu

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2128]
Once the various page updates are done we need to update the menu to take those changes into account.

* Careers page: #2124 
* Values page: #2123 
* Join our team: #2124 
* Job posting page: #1729 

What should the new menu contain?

**Comment by victoriachanimal** [comment]
Thanks @dj2 ! We have a [proposed site map](https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Copy-w-March-2021-Updates?node-id=64%3A1329) for the website redesign, and for the Talent-related pages, the idea is the bring "Careers" (#2124) back to the main menu (it's currently only linked directly through the "Who we are" page, which is on the main menu).

As part of the plan, when someone hovers over "Careers" on the main menu, a drop down menu could display accompanying pages including "Values" (#2123 ) and "Join our team" (#2124) — Figma mockup can be found [here](https://www.figma.com/file/LW1JsT0h3IY2trMHdIVDQc/CDS-Website-Copy-w-March-2021-Updates?node-id=123%3A2349). 

^ Individual job postings (#1729) will be directly listed on the "Careers" (#2124) page, so I think these don't need to go under the Careers drop down, as there could be many job postings at a given time. 

Happy to chat more and collab on the best approach to display these pages.
