### ISSUE TITLE
Fixup aria parent item for basic HTML version link.

### ISSUE THREAD

**Issue by dj2** [cds-snc/digital-canada-ca#2130]
The 'Switch to basic HTML' link needs to have the parent element updated to not have a `role` or to have a role of `list`.

```
<li class="wb-slc"><a class="wb-sl" rel="alternate" href="?wbdisable=true">Switch to basic HTML version</a></li>
```

See https://dequeuniversity.com/rules/axe/4.1/listitem for more context.

**Comment by dj2** [comment]
I can't actually find this on the page at the moment. It's possible the accessibility report is doing something different, running without JS or something else. Need to investigate why this is getting reported as an error.

**Comment by brdunfield** [comment]
Which accessibility report did you use? I've run the Axe Dev tools and accessibility insights and neither reported this. I don't see any roles on the parent <li> or <ul> either 🤔

**Comment by dj2** [comment]
This doesn't appear to be showing up anymore, maybe it got fixed?

I was using the https://a11y-tools-query.herokuapp.com/revisions/cds-snc%2Fdigital-canada-ca/3df90eeddf648310fdfdce762b6d34d571b8e445 report (though, not that specific revision) when I saw this. Will link the report in the future.
