### ISSUE TITLE
Home Page : Heading elements are not in a sequentially-descending order

### ISSUE THREAD

**Issue by ppyang** [cds-snc/digital-canada-ca#2288]
Hi, I'm browsing the website and found the home page didn't get Chrome's Lighthouse 100% score for accessibility. 

The offending element is this： 

![image](https://user-images.githubusercontent.com/838759/119694481-40790700-be1b-11eb-9d9c-f3e001e6160c.png)

It might be because there's no h3 tag between h2 and h4. 

Thanks and have a great day!

**Comment by dj2** [comment]
The change to fix this was reverted. The fix had other accessibility issues, which while fixing this issue, we thought were in the wrong direction. Reopening this so we don't lose track.
