### ISSUE TITLE
Search function improvements

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/digital-canada-ca#2727]
Hello! 

Search looks pretty good and it is pretty responsive, but it has some issues that are worth fixing.

Here is a gif I made of some things to look into.

![Screen Recording 2021-11-04 at 17 47 51](https://user-images.githubusercontent.com/2454380/140428814-48d15801-f94d-4ea6-89e0-5469f9a1c4b1.gif)

### Bugs
- [x] Search doesn't work with any capital letters: eg, `Health Canada` or `COVID` (same as #2726)
- [x] Search doesn't always work with partial matches: eg, `informa` doesn't match `information` (although, `info` and `inform` do)
- [x] Search doesn't work with punctuation: eg, `wi-fi` or `post,`
- [x] Search doesn't work with spaces: eg, `blog post` or `COVID Alert`
- [x] It's possible for focus to move out of the search modal: eg, if you tab past results, or reload when the search modal is open

### Suggestions
- [x] The aria-label for the search button says "Open". It should probably say "Search"
- [x] The "Load more" button isn't keyboard accessible (normally buttons can be triggered with the space bar)
- [x] The "14 results" string should maybe have some kind of "alert" role for announcing to screen readers

**Comment by omartehsin1** [comment]
Thanks, Paul. Will look into these!
