### ISSUE TITLE
When CVs are uploaded to job application, either blank or not converted to PDF

### ISSUE THREAD

**Issue by Charcharbinkz** [cds-snc/digital-canada-ca#2732]
From @brockhigg10: 
CVs blank: CVs being attached to applications are either blank or not PDF.  The not PDF is not the issue, but majority of the PDF CVs being submitted are displaying as blank.

**Comment by omartehsin1** [comment]
Fixed by Max with the following:

https://github.com/cds-snc/cds-web-form/commit/cfd9e0090cdf63de4af744709ade207c43d05c12
