### ISSUE TITLE
GC logo doesn't look as sharp on a 1080p screen 

### ISSUE THREAD

**Issue by Charcharbinkz** [cds-snc/digital-canada-ca#2779]
"Small FIP :bug:: On a 1080p screen the GC logo gets downsampled and no longer looks sharp."

https://gcdigital.slack.com/archives/CG00PTC5R/p1637851748103900

**Comment by victoriachanimal** [comment]
Team did some testing on this (via different screen widths) and weren't able to find or locate when the GC logo loses quality. We use them same SVG throughout, only swapping when it switches to the square on phone screens so it this could also be a setting on individual browsers/devices causing the drop in quality. 

We've decided to close this issue for now but will definitely revisit if we get more info.
