### ISSUE TITLE
French versions of GoC logo and CDS logo

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/digital-canada-ca#2821]
Hi there!

Just a bit of housekeeping here, nothing urgent.

This issue is about adding French versions of the GoC FIP logo and the CDS logo / wordmark.

When you're on a Canada.ca site, switching between French and English pages results in the FIP logo changing between a French and an English version in which the priority of the text changes. (The `aria-label` changes as well, but you are already doing this, so this issue is solely about the image.) 

You can see the text changes places: the English one has the English description come first, and the French is the opposite.

| FIP English | FIP French |
|-------------|------------|
|    <img width="376" alt="Screen Shot 2021-12-14 at 16 50 25" src="https://user-images.githubusercontent.com/2454380/146085854-cc9fb4db-7227-4881-ad0b-381ed264ac1a.png">    |  <img width="376" alt="Screen Shot 2021-12-14 at 16 50 16" src="https://user-images.githubusercontent.com/2454380/146085851-1a6e4249-5dc1-432a-b0b3-6d19b69c313f.png">    |

On GC Articles, we are working on a story to link to the French login page, so I've done the same thing with our `.svg` CDS logo (also changing the little initials inside of the black box).

| CDS logo English (current) | CDS logo French |
|-------------|------------|
|   <img width="343" alt="Screen Shot 2021-12-14 at 16 49 33" src="https://user-images.githubusercontent.com/2454380/146086261-7fbda8da-72c5-4304-aeeb-b9ccb58df8a8.png">   |   <img width="343" alt="Screen Shot 2021-12-14 at 16 49 45" src="https://user-images.githubusercontent.com/2454380/146086262-e68fac1d-d3aa-4bcf-af4f-b5238dd46af4.png">    |

If you want the `.svg` we are using, you can grab it here: https://github.com/cds-snc/gc-articles/pull/414/files#diff-fcbf7d7b4099ad7f9884a8b22032e7e8e8578d5611619e53a54f5b632425e28d

**Comment by omartehsin1** [comment]
I actually noticed the aria-label also seems to be missing, only FR is available for both FR and EN

@Charcharbinkz the aria-label for the CDS logo is only in FR as "Accéder à la page d'accueil", is this the right content? If so, I'll have the translation team get the EN translation of this.

**Comment by Charcharbinkz** [comment]
Awesome, thanks for catching that @omartehsin1 . 

That sounds like a good aria-label for the logo. For English, it can be "Go to the homepage."
