### ISSUE TITLE
Individual job postings repeating H1 job titles at top of page

### ISSUE THREAD

**Issue by Charcharbinkz** [cds-snc/digital-canada-ca#3195]
Noticed that individual job postings have 2 H1s with the same information. Is this a Strapi input error, or something strapi is duplicating? 

Ex: https://digital.canada.ca/careers/positions/consulting-digital-practitioner-research-and-service-design-09bc4216-04f8-4e70-b2af-be70e6bc3c9c/
<img width="784" alt="Screen Shot 2022-03-30 at 10 43 35 AM" src="https://user-images.githubusercontent.com/42043272/160862577-d6692508-58f2-4103-b7ad-72c19f3d3977.png">

**Comment by Charcharbinkz** [comment]
Also noticing some repetition at the bottom: 
<img width="1083" alt="Screen Shot 2022-03-30 at 10 48 55 AM" src="https://user-images.githubusercontent.com/42043272/160863658-586d8bb3-3e79-4767-9cdc-1949ce7ce0a6.png">

**Comment by victoriachanimal** [comment]
Thanks for flagging @Charcharbinkz! 

For the text repetition, the section "Work anywhere in Canada" is part of a built-in template that is featured automatically in every job posting. 

<img width="1031" alt="Screen Shot 2022-03-30 at 11 59 24 AM" src="https://user-images.githubusercontent.com/39972942/160879254-c46abb9e-a015-4f30-81da-7dbf8ef855b8.png">

I know the Linguistics team is working on creating a template to help standardize job postings that ppl in the org could refer to... perhaps we could connect with them to see how could clarify content in a job posting that will automatically be added so its not duplicated? Lmk your thoughts.

**Comment by Charcharbinkz** [comment]
Yeah, totally! Template is awesome. Maybe content authors just aren't aware of the standard info that's autogenerated, like assessment accommodation etc.

**Comment by omartehsin1** [comment]
@Charcharbinkz @victoriachanimal , should I remove the repeated text that's built in to the template or are we going to advise talent not to include it?

**Comment by Charcharbinkz** [comment]
Hi @omartehsin1! [This PR fixes duplicate links and texts.](https://github.com/cds-snc/digital-canada-ca/pull/3213) Though I noticed in Strapi that the title wasn't added twice, so I don't think that duplication is something I can fix through there :( Would that be something you'd have to do on your end?

**Comment by victoriachanimal** [comment]
Hey @Charcharbinkz @omartehsin1 ! Sorry for the confusion. So for the H1 titles specifically, I believe that would require us to do some work on Strapi itself as it is an automatic field in the CMS, and inputting a job title via for any job post via Strapi makes it automatically appear as two H1s (the bigger and smaller one) on a page.

**Comment by omartehsin1** [comment]
@Charcharbinkz @victoriachanimal, I can simply remove where the title gets added twice:

https://github.com/cds-snc/digital-canada-ca/pull/3214
