### ISSUE TITLE
Figuring out what happens to old job postings: adjust tone on 404 pages or update archived pages to make more obvious that we are no longer accepting applications.

### ISSUE THREAD

**Issue by Charcharbinkz** [cds-snc/digital-canada-ca#3340]
Leah noted that the language on our 404 pages might come across as flippant to job seekers who are trying to find a job posting that no longer exists: 

[English](https://digital.canada.ca/go)
[French](https://numerique.canada.ca/go)

It raised the question about what happens to old job postings: Do they get removed and links are no longer active (ie people see 404) or do they get archived and links are still active but the application form is removed? Talent prefers the latter and under the assumption it was the latter. But talent noted some links no longer exist, like the CEO poster. 

- [x] find out what happens to past job postings? Do we have different criteria for what happens to them depending on the job? Does it depend on if they were added before Strapi implementation?

**If removed completely:** 
- [ ] update 404 languages to be more respectful of what might be a frustrating experience for users

**If form removed but link still active:**
- [ ] Is there a way to auto add a disclaimer to top of page stating that this is an old job posting?

**Comment by omartehsin1** [comment]
This is an inactive job posting:

https://digital.canada.ca/careers/positions/internal-communications-advisor-588bfcdb-d182-43c5-a5aa-27a23f71b01f/

It doesn't get removed entirely, it is still available to view but users can no longer apply to the job. We can add a disclaimer something along the lines of "this post is no longer taking applications"

**Comment by Charcharbinkz** [comment]
I think that could be a helpful fix! Thanks!

I'll think about a phrase we could use and run it by Leah. Once it's approved and translated, I'll add it back here.
