### ISSUE TITLE
Review non-breaking spaces in converted / new markdown posts

### ISSUE THREAD

**Issue by brdunfield** [cds-snc/digital-canada-ca#343]

**Comment by khalidelaggan** [comment]
Just looking at this now, and I believe this has already been fixed a while ago

**Comment by khalidelaggan** [comment]
Hello @brdunfield just to clarify before attempting to close this issue that your concerns have been addressed?

I'm also happy to assist with anything needed.

Thanks!

**Comment by khalidelaggan** [comment]
Thank you @dsamojlenko for working on resolving these issues
