### ISSUE TITLE
Team page image size

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/digital-canada-ca#346]
The total page downloads about 40 MB because the images are still at their native resolution. They look great though!

**Comment by brdunfield** [comment]
This is already in progress to be fixed! 👍

**Comment by timarney** [comment]
Outside of making the images smaller for a performance / future build.

Some sort of lazy loading setup would be good - intersection-observer has decent support these days.  

Something like:
https://scotch.io/tutorials/lazy-loading-images-for-performance-using-intersection-observer

Or there's some nice services that have decent free tiers i.e. https://cloudinary.com to the rescue.

**Comment by brdunfield** [comment]
Addressed in #391 but leaving open for now, as images are still larger than they used to be. Will close if the current size is deemed acceptable.

**Comment by steve-h** [comment]
I found this test site useful for my performance tuning. I was able to score straight "A"s after a few days of investigation.
[webpagetest.org](https://www.webpagetest.org)
Your main page also does not perform that well.

**Comment by obrien-j** [comment]
![image](https://user-images.githubusercontent.com/17616596/50578960-92660000-0e0e-11e9-9f81-46f68c29f0ee.png)

Just going to bump this as load time for me, on a fibe link was 3.3 minutes.

**Comment by maxneuvians** [comment]
We can either lazy load, or cloudinary, or even run them through something like this: https://imagecompressor.com/ which I usually use to get things to like 40kb

**Comment by timarney** [comment]
I'm game to jump in on this and set up something like https://gohugo.io/content-management/image-processing has https://github.com/muesli/smartcrop built in.

@brdunfield let me know your thoughts.

**Comment by brdunfield** [comment]
@timarney this looks really nice!
Things that can be done through Hugo are preferable, since ideally we want comms to just be able to manage team photos without a dev having to go compress everything after every update.

I'll work on it this week.

**Comment by timarney** [comment]
Images are now processed with a Node script + Github actions.

**Comment by timarney** [comment]
This would be worth adding at this point.

https://addyosmani.com/blog/lazy-loading

**Comment by khalidelaggan** [comment]
I will look into this and will added to our next sprint scope

**Comment by khalidelaggan** [comment]
#1062

**Comment by khalidelaggan** [comment]
Per @timarney recommendation, image lazy-loading is now integrated and deployed to the live site.
