### ISSUE TITLE
Image assets on most recent accessibility blog is unnecessarily large.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/digital-canada-ca#576]
https://digital.canada.ca/img/cds/_mg_9837-2.jpg <-- this high res image (10-11mbs) is being used on the main homepage as a thumbnail, causing a pretty unnecessary spike in traffic/costing, and ironically, likely making the website less accessible without high bandwidth links.

Suggest we just shrink it out of band until the #453 gets pushed through...

**Comment by timarney** [comment]
This is automated now. 

When a new PR comes in via Netlify the images will be processed via Github Actions

<img width="914" alt="screen shot 2019-02-20 at 1 54 55 pm" src="https://user-images.githubusercontent.com/62242/53116684-3c146400-3517-11e9-86fb-18bfad163aaa.png">

🎉 @maxneuvians @dsamojlenko
