### ISSUE TITLE
text in header was being truncated

### ISSUE THREAD

**Issue by scilib** [cds-snc/digital-canada-ca#7]
Before the pause button was added, the header text was being truncated at "to" (not displaying "use") on iPhone 6S Safari.
![cds easy to](https://user-images.githubusercontent.com/3245833/28460342-97d12bd0-6ddf-11e7-87f1-d9f616ad0a46.jpg)

**Comment by mcman12** [comment]
we've been trying to replicate but weren't able to on the 6s. we will be looking at this.
thanks.

**Comment by sboots** [comment]
Hi @scilib - any updates on the text in the header on the iPhone 6S, now that the pause button is there? Or is it looking okay now? Thanks! #fixingthingsbyaccident

**Comment by scilib** [comment]
It looks good now.  I forgot to mention that I was operating in Display Zoomed mode (Settings->Display & Brightness->Display Zoom - View - Zoomed).  That's a display mode to make sure you test against.
