### ISSUE TITLE
Remove Windows carriage returns in ^M

### ISSUE THREAD

**Issue by mgifford** [cds-snc/digital-canada-ca#75]
Ran into an annoying error with `./serve ` that was due to Windows carriage returns. 

https://halimdba.blogspot.ca/2016/06/binshm-bad-interpreter-no-such-file-or.html

**Comment by dsamojlenko** [comment]
Fixed in #76 - You will need to re-clone the repo after this change for this to have an affect.

This is due to how windows treats line endings.  You can fix this globally in your git config as well by running `git config --global core.autocrlf true`

**Comment by mgifford** [comment]
thanks!
