### ISSUE TITLE
Broken Link on "Beginning the Conversation" Engagement Report

### ISSUE THREAD

**Issue by krutkay** [cds-snc/digital-canada-ca#776]
I fixed a number of broken links in PR #775, but there is one outstanding link that I could not find a "correct" link for.  There's a link [on this page](https://digital.canada.ca/beginning-the-conversation/full-report/) to New Zealand's Digital Transformation Team, which links to a now defunct blog post.

I'm not sure what was contained on the original page, but maybe one of the links below would be an appropriate substitute (or perhaps the hyperlink should be removed entirely):

- https://www.digital.govt.nz/digital-government/digital-transformation/nz-digital-transformation/
- https://www.digital.govt.nz/home/about-digital-govt-nz

**Comment by timarney** [comment]
@sboots any ideas for this one?

**Comment by lynnchalati** [comment]
It might be this: 
https://www.digital.govt.nz/digital-government/digital-transformation/nz-digital-transformation/

**Comment by lynnchalati** [comment]
I'm double checking with @wendymluciani and John Millons.

**Comment by lynnchalati** [comment]
Okay confirmed. Let's go with:

https://www.digital.govt.nz/digital-government/digital-transformation/nz-digital-transformation/

great catch!
