### ISSUE TITLE
i18n plugin

### ISSUE THREAD

**Issue by nschonni** [cds-snc/digital-canada-ca#9]
Since you're not doing the gh-pages publishing anymore, you might want to look at https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

**Comment by dsamojlenko** [comment]
yes! that is definitely in the hopper now that it's available to us... thanks!

**Comment by dsamojlenko** [comment]
Had a look at the plugin, and it didn't quite fit with the way we build our site... closing this for now, but may revisit in future.
